local function set_rands(self)
    self.rand_aim = vmath.vector4(math.min(0.2, math.random()), math.min(0.9, math.random()), math.min(0.3, math.random()), math.min(0.3, math.random()))
end

function init(self)
    self.time = 0

    self.rand_current = vmath.vector4()
    self.rand_aim = vmath.vector4(math.min(0.2, math.random()), math.min(0.9, math.random()), math.min(0.3, math.random()), math.min(0.3, math.random()))

    timer.delay(6, true, set_rands)
end

function update(self, dt)
	local width, height = window.get_size()

    self.time = self.time + dt

    local ship_pos = go.get_position("/ship")
    go.set("#model", "bg_ship", vmath.vector4(ship_pos.x * 0.01, 0,0,0))
    go.set("#model", "bg_const", vmath.vector4(self.time * 1, math.max(width, height), width, height))

    self.rand_current = vmath.lerp(dt * 0.2, self.rand_current, self.rand_aim)
    go.set("#model", "bg_rands", self.rand_current)

    if self.play_video then
        --go.set("/video#model", "inputs", vmath.vector4(self.time, 0, 0, 0))
    end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("stop_video") then
        self.play_video = false
    elseif message_id == hash("start_video") then
        self.play_video = true
    end
end