local function set_rands(self)
    self.rand_aim = vmath.vector4(math.min(0.2, math.random()), math.min(0.9, math.random()), math.min(0.3, math.random()), math.min(0.3, math.random()))
end

function init(self)
    self.time = 0

    self.rand_current = vmath.vector4()
    self.rand_aim = vmath.vector4(math.min(0.2, math.random()), math.min(0.9, math.random()), math.min(0.3, math.random()), math.min(0.3, math.random()))

    timer.delay(6, true, set_rands)
end

function update(self, dt)
	local width, height = window.get_size()

    self.time = self.time + dt

    go.set("#model", "bg_const", vmath.vector4(self.time, math.max(width, height), width, height))

    self.rand_current = vmath.lerp(dt * 0.2, self.rand_current, self.rand_aim)
    go.set("#model", "bg_rands", self.rand_current)
end