go.property("speed", 200)
go.property("acceleration", 1.02) -- exponential factor

function init(self)
	timer.delay(2, false, function (self, handle, time_elapsed)
		go.delete()
	end)
end

function update(self, dt)
	local pos = go.get_position()
	pos.y = pos.y + self.speed * dt
	go.set_position(pos)
	self.speed = self.speed * self.acceleration

	local scale = go.get_scale()
	scale.y = math.min(4, self.speed / 300)
	go.set_scale(scale)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		particlefx.play("#particle")

		go.delete()
	end
end