function init(self)
    msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
    local cursor_pos = camera.screen_to_world(vmath.vector3(action.screen_x, action.screen_y, 500), "/camera#camera")

    action.x = cursor_pos.x
    action.y = cursor_pos.y
    action.z = -500

    msg.post("/cursor#cursor", hash("input"), {action_id = action_id, action = action})
    msg.post("/ship", "move_to_cursor", {position = vmath.vector3(action.x, action.y, action.z)})

    if action_id == hash("touch") then
        msg.post("/ship", "fire")
    end
end