go.property("queue", 0)

local function complete_function(self, url, property)
	go.animate(".", "position.y", go.PLAYBACK_ONCE_PINGPONG, self.go_to_y, go.EASING_INBACK, 2, self.delay, complete_function)
end

function init(self)
	self.health = 3
	self.can_get_hurt = true

	self.delay = 0.1
    self.go_to_y = go.get_position().y + 20
	go.animate(".", "position.y", go.PLAYBACK_ONCE_PINGPONG, self.go_to_y, go.EASING_INBACK, 2, self.delay * self.queue, complete_function)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and self.can_get_hurt then
		local timer_handle = timer.delay(0.0000001, false, function (self, handle, time_elapsed)
			self.can_get_hurt = true
		end)

		self.can_get_hurt = false

		local go_to_y = go.get_position().y + 5
		go.animate(".", "position.y", go.PLAYBACK_ONCE_PINGPONG, go_to_y, go.EASING_INBACK, 0.1)

		self.health = self.health - 1
		if self.health <= 0 then
			timer.cancel(timer_handle)
			go.cancel_animations(".", "position.x")
			go.cancel_animations(".", "position.y")

			self.can_get_hurt = false

			local go_to_y2 = go.get_position().y - 300
			local go_to_x = go.get_position().x + 100 * (math.random(0, 1) * 2 - 1)

			msg.post("#collisionobject", "disable")

			go.animate(".", "position.x", go.PLAYBACK_ONCE_FORWARD, go_to_x, go.EASING_INCIRC, 1)
			go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, go_to_y2, go.EASING_INBACK, 0.5, 0.0, function (self, url, property)
				go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, go_to_y2 - 800, go.EASING_LINEAR, 0.2, 0.0, function (self, url, property)
					msg.post("/top_bar/bar_controller", "letter_down")
					go.delete()
				end)
			end)
		end
	end
end