go.property("queue", 0)

local function complete_function(self, url, property)
    go.animate(".", "position.y", go.PLAYBACK_ONCE_PINGPONG, self.go_to_y, go.EASING_INBACK, 2, self.delay, complete_function)
end

function init(self)
    self.delay = 0.1
    self.go_to_y = go.get_position().y + 20

    go.animate(".", "position.y", go.PLAYBACK_ONCE_PINGPONG, self.go_to_y, go.EASING_INBACK, 2, self.delay * self.queue, complete_function)
end