local function check_aspect_change(self)
	local before = self.is_width

	local width, height = window.get_size()
	self.is_width = width > height

	return before ~= self.is_width
end

local function scale_whole_table(table, is_small)
	for _, value in pairs(table) do
		if is_small then
			go.set_scale(value.scale * 0.5, value.url)
		else
			go.set_scale(value.scale, value.url)
		end
	end
end

local function scale(self, event, data, is_start)
	if check_aspect_change(self) or is_start then
		if self.is_width then
			scale_whole_table(self.game_objects, false)
		else
			scale_whole_table(self.game_objects, true)
		end
	end
end

function init(self)
	self.game_objects = {}

	scale(self, nil, nil, true)

	window.set_listener(scale)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("subscribe") then
		local go_inits = {url = sender, scale = go.get_scale(sender)}
		table.insert(self.game_objects, go_inits)

		scale(self, nil, nil, true)
	end
end
