local CURRENT_COLOR = vmath.vector4(0.23, 1, 0.1, 1)
local PAST_COLOR = vmath.vector4(0.7, 0.2, 0.6, 1)
local WAIT_COLOR = vmath.vector4(1, 1, 1, 1)

local urls = {
        "/top_bar/start",
        "/top_bar/experience",
        "/top_bar/education",
        "/top_bar/programming",
        "/top_bar/design",
        "/top_bar/CV"
    }

local counts = {
        1,
        1,
        1,
        1,
        1,
        1,
    }

local letters = {
        26,
        1,
        1,
        1,
        1,
        1,
    }

local function set_color_label(current_page)
    go.animate(urls[current_page - 1] .. "#label", "color", go.PLAYBACK_ONCE_FORWARD, PAST_COLOR, go.EASING_LINEAR, 0.3)
    go.animate(urls[current_page] .. "#label", "color", go.PLAYBACK_ONCE_FORWARD, CURRENT_COLOR, go.EASING_LINEAR, 0.3)
end

local function set_color_label_back(current_page)
    go.animate(urls[current_page + 1] .. "#label", "color", go.PLAYBACK_ONCE_FORWARD, WAIT_COLOR, go.EASING_LINEAR, 0.3)
    go.animate(urls[current_page] .. "#label", "color", go.PLAYBACK_ONCE_FORWARD, CURRENT_COLOR, go.EASING_LINEAR, 0.3)
end

local function set_color_circles(current_page)
    for i = 1, 7 do
        timer.delay(0.1 * (7 - i), false, function ()
            local index = i == 1 and "" or i - 1
            go.set(urls[current_page - 1] .. "_circles#sprite" .. index, "tint", PAST_COLOR)
        end)
    end
end

local function set_color_circles_back(current_page)
    for i = 1, 7 do
        timer.delay(0.1 * i, false, function ()
            local index = i == 1 and "" or i - 1
            go.set(urls[current_page] .. "_circles#sprite" .. index, "tint", WAIT_COLOR)
        end)
    end
end

go.property("shock_time", 0)
local function next(self)
    counts[self.current_page] = counts[self.current_page] - 1
    if counts[self.current_page] > 0 then
        return
    end

    self.current_page = self.current_page + 1
    set_color_label(self.current_page)
    set_color_circles(self.current_page)

    self.cursor_pos = camera.world_to_screen(go.get_position("/ship"), "/camera#camera")
    go.animate("#", "shock_time", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_INSINE, 1, 0, function (self, url, property)
        self.cursor_pos = vmath.vector3(-100000, -100000, 0)
    end)
end

function init(self)
    self.cursor_pos = vmath.vector3()
    self.current_page = 1

    go.set(urls[1] .. "#label", "color", CURRENT_COLOR)
end

function update(self, dt)
    go.set("/postprocess#model", "u_in", vmath.vector4(self.cursor_pos.x, self.cursor_pos.y, self.shock_time, 0))
end

function on_message(self, message_id, message, sender)
    if message_id == hash("prev") then
        self.current_page = self.current_page - 1
        set_color_label_back(self.current_page)
        set_color_circles_back(self.current_page)
    elseif message_id == hash("letter_down") then
        letters[self.current_page] = letters[self.current_page] - 1
        if letters[self.current_page] <= 0 then
            next(self)
        end
    end
end
