go.property("playback_speed", 1)
go.property("file_count", 1)

local function close(self)
	if self.video then
		mpeg.close(self.video)
		self.video = nil
		self.video_data = nil
		self.streaming_data = nil
	end
end

local function open(self, filename)
	close(self)

	local options = {
		audio = false,
		loop = true,
	}
	self.video_data = resource.load(filename)
	local video, err = mpeg.open(self.video_data, options)
	if err then
		self.video_data = nil
		error(err)
		return
	end
	self.video = video
end

function init(self)
	self.frame_count = 0
	--stream(self, VIDEONAME)
	open(self, "/videos/video" .. self.file_count .. ".mpeg")
	self.is_enable = true

	self.health = 15
	self.can_get_hurt = true

	msg.post("/bg#animate_bg", "start_video")
end

function final(self)
	close(self)
	
	msg.post("/bg#animate_bg", "stop_video")
end

function update(self, dt)
	if not self.is_enable then
		return
	end

	self.frame_count = self.frame_count + 1
	if not self.video then
		return
	end
	if self.playback_speed == 0 then
		return
	end

	local info = mpeg.get_info(self.video)

	-- check if the video is streaming and if it needs any bytes
	if info.is_streaming and self.frame_count % 5 == 0 then
		local bytes_needed = info.streaming_buffer_capacity - info.streaming_buffer_bytes_remaining
		if bytes_needed > 0 then
			local from = self.streaming_data_index
			local to = math.min(#self.streaming_data, from + bytes_needed - 1)
			local amount = to - from + 1
			self.streaming_data_index = self.streaming_data_index + amount

			local bytes = self.streaming_data:sub(from, to)
			mpeg.write(self.video, bytes)

			if from > #self.streaming_data then
				mpeg.rewind(self.video)
				self.streaming_data_index = 0
			end
		end
	end

	-- decode video
	mpeg.decode(self.video, dt * self.playback_speed)

	-- get a video frame and update the texture
	local videoframe = mpeg.get_frame(self.video)
	if videoframe then
		local videoheader = { width=info.width, height=info.height, type=resource.TEXTURE_TYPE_2D, format=resource.TEXTURE_FORMAT_RGB, num_mip_maps=1 }
		local path = go.get("#model", "texture1")
		resource.set_texture(path, videoheader, videoframe)
	end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("disable") then
        self.is_enable = false
    elseif message_id == hash("enable") then
        self.is_enable = true
	elseif message_id == hash("collision_response") and self.can_get_hurt then
		local timer_handle = timer.delay(0.0000001, false, function (self, handle, time_elapsed)
			self.can_get_hurt = true
		end)

		self.can_get_hurt = false

		self.health = self.health - 1
		if self.health <= 0 then
			timer.cancel(timer_handle)

			self.can_get_hurt = false

			local go_to_y2 = go.get_position().y - 1000
			local go_to_x = go.get_position().x + 650 * (math.random(0, 1) * 2 - 1)

			msg.post("#collisionobject", "disable")

			go.animate(".", "position.x", go.PLAYBACK_ONCE_FORWARD, go_to_x, go.EASING_INCIRC, 1)
			go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, go_to_y2, go.EASING_INBACK, 0.5, 0.0, function (self, url, property)
				go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, go_to_y2 - 800, go.EASING_LINEAR, 0.2, 0.0, function (self, url, property)
					msg.post("/top_bar/bar_controller", "letter_down")
					go.delete()
				end)
			end)
		end
	end
end