go.property("playback_speed", 1)
go.property("file_count", 1)

local function close(self)
	if self.video then
		mpeg.close(self.video)
		self.video = nil
		self.video_data = nil
		self.streaming_data = nil
	end
end

local function open(self, filename)
	close(self)

	local options = {
		audio = false,
		loop = true,
	}
	self.video_data = resource.load(filename)
	local video, err = mpeg.open(self.video_data, options)
	if err then
		self.video_data = nil
		error(err)
		return
	end
	self.video = video
end

function init(self)
	self.frame_count = 0
	--stream(self, VIDEONAME)
	open(self, "/videos/video" .. self.file_count .. ".mpeg")
end

function final(self)
	close(self)
end

function update(self, dt)
	if not self.is_enable then
		return
	end

	self.frame_count = self.frame_count + 1
	if not self.video then
		return
	end
	if self.playback_speed == 0 then
		return
	end

	local info = mpeg.get_info(self.video)

	-- check if the video is streaming and if it needs any bytes
	if info.is_streaming and self.frame_count % 5 == 0 then
		local bytes_needed = info.streaming_buffer_capacity - info.streaming_buffer_bytes_remaining
		if bytes_needed > 0 then
			local from = self.streaming_data_index
			local to = math.min(#self.streaming_data, from + bytes_needed - 1)
			local amount = to - from + 1
			self.streaming_data_index = self.streaming_data_index + amount

			local bytes = self.streaming_data:sub(from, to)
			mpeg.write(self.video, bytes)

			if from > #self.streaming_data then
				mpeg.rewind(self.video)
				self.streaming_data_index = 0
			end
		end
	end

	-- decode video
	mpeg.decode(self.video, dt * self.playback_speed)

	-- get a video frame and update the texture
	local videoframe = mpeg.get_frame(self.video)
	if videoframe then
		local videoheader = { width=info.width, height=info.height, type=resource.TEXTURE_TYPE_2D, format=resource.TEXTURE_FORMAT_RGB, num_mip_maps=1 }
		local path = go.get("#sprite", "texture0")
		resource.set_texture(path, videoheader, videoframe)
	end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("disable") then
        self.is_enable = false
    elseif message_id == hash("enable") then
        self.is_enable = true
    end
end