embedded_components {
  id: "label"
  type: "label"
  data: "size {\n"
  "  x: 128.0\n"
  "  y: 32.0\n"
  "}\n"
  "color {\n"
  "  x: 0.8\n"
  "  y: 0.8\n"
  "  z: 0.8\n"
  "}\n"
  "shadow {\n"
  "  x: 0.5019608\n"
  "  y: 0.7019608\n"
  "  z: 0.5019608\n"
  "}\n"
  "pivot: PIVOT_W\n"
  "text: \"a\\n"
  "\"\n"
  "  \"\"\n"
  "font: \"/font/fancy_font.font\"\n"
  "material: \"/builtins/fonts/label-df.material\"\n"
  ""
}
