components {
  id: "video_player"
  component: "/scripts/video_player.script"
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/builtins/assets/meshes/quad_2x2.dae\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/shaders/sprite_smoth_big.material\"\n"
  "  textures {\n"
  "    sampler: \"texture_sampler\"\n"
  "    texture: \"/assets/video_textures/video1.png\"\n"
  "  }\n"
  "  textures {\n"
  "    sampler: \"mask\"\n"
  "    texture: \"/assets/mask.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"label\"\n"
  "mask: \"bullet\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 1.5\n"
  "  data: 0.95\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
